version: '3.5'

volumes:
  mongo_data:
    external: 
      name: mongo_data

networks: 
  databases:
  views:

services: 
  gateway:
    build:
      context: ./
      args:
      - src=gateway
    image: gateway:latest
    deploy:
      replicas: 1
    ports:
      - 2000:2000
    command: npm run dev
    networks: 
      - databases
      - views

  signin:
    build: 
      context: ./
      args:
      - src=signin
    image: signin:latest
    ports:
      - 2221:2221
    command: npm run dev
    links:
      - db
    networks: 
      - databases
    deploy:
      replicas: 1

  signup:
    build: 
      context: ./
      args:
      - src=signup
    image: signup:latest
    deploy:
      replicas: 1
    ports:
    - 2222:2222
    command: npm run dev
    links:
    - db
    networks: 
      - databases
    
      
  db:
    image: mongo
    deploy:
      replicas: 1
    ports:
      - "27017"
    volumes:
      - mongo_data:/data/db
    networks: 
      - databases
    