version: '3'

services: 

    signin:
        build: 
            context: ./
            args:
            - src=signin
        expose:
            - ${PORT_SIGNIN}
        ports:
            - ${PORT_SIGNIN}:${PORT_SIGNIN}
        command: npm run dev
        links:
          - mongo
    
    mongo-express:
        image: mongo-express
        ports:
          - 8081:8081
        environment:
          ME_CONFIG_BASICAUTH_USERNAME: user
          ME_CONFIG_BASICAUTH_PASSWORD: user
          ME_CONFIG_MONGODB_PORT: 27017
          ME_CONFIG_MONGODB_ADMINUSERNAME: admin
          ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ADMIN_PASSWORD}
        links:
          - mongo
        networks:
          - test
      
    mongo:
        image: mongo
        environment:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASSWORD}
        ports:
         - "27017:27017"
        volumes:
         - /mongo_data:/data/db
        networks:
         - test
    
    networks: 
        test:
        driver: bridge
