version: '3.5'

services: 

    signin:
        build: 
            context: ./
            args:
            - src=signin
        expose:
            - ${PORT_SIGNIN}
        ports:
            - ${PORT_SIGNIN}:${PORT_SIGNIN}
        command: npm run dev
        links:
          - db

    signup:
        build: 
          context: ./
          args:
          - src=signup
        expose:
          - ${PORT_SIGNUP}
        ports:
          - ${PORT_SIGNUP}:${PORT_SIGNUP}
        command: npm run dev
        links:
        - db
        
    db:
        image: mongo
        ports:
         - "27017:27017"
        volumes:
         - /mongo_data:/data/db
