version: '3.8'

volumes:
  mongo_data:
      name: mongo_data

networks: 
  databases:

services: 

  signin:
    build: 
      context: ./
      args:
      - src=signin
    image: signin:latest
    ports:
      - 2221:2221
    command: npm run dev
    networks: 
      - databases
    deploy:
      replicas: 1

  signup:
    build: 
      context: ./
      args:
      - src=signup
    image: signup:latest
    ports:
    - 2222:2222
    command: npm run dev
    networks: 
      - databases
    deploy:
      replicas: 1
      
  db:
    image: mongo
    ports:
      - "27017"
    volumes:
      - mongo_data:/data/db
    networks: 
      - databases
    deploy:
      replicas: 1