version: '3'

services: 
    signin:
        build: 
            context: ./
            args:
            - src=signin
        expose:
            - ${PORT_SIGNIN}
        ports:
            - ${PORT_SIGNIN}:${PORT_SIGNIN}
        command: npm run dev
